#This will create this metric in all the tiers, under this path. Please make sure to have a trailing |
#metricPrefix: "Custom Metrics|Amazon Custom Namespace|"

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Amazon Custom Namespace|"

accounts:
  - awsAccessKey: ""
    awsSecretKey: ""
    displayAccountName: "AppD Custom"

    # Regions where customnamespace is registered
    # Allowed values: Please refer to regionEndPoints configuration in this file.
    regions: ["us-west-2", "us-east-1"]
    

# Please specify the namespace that you would like to monitor. AWS/ElasticBeanstalk is just an example. Please change this to your need.
namespace: "AWS/DynamoDB"

# Password Encryption
credentialsDecryptionConfig:
    enableDecryption: "false"
    encryptionKey: ""

# configure proxy if any
proxyConfig:
    host:
    port:
    username:
    password:


dimensions:
  - name: "TableName"
    displayName: "Table Name"
    values: ["ABC"]
  - name: "AvailabilityZone"
    displayName: "Availability Zone"
    values: []

# Global metrics config for all accounts
metricsConfig:

    # By default, all metrics retrieved from cloudwatch are 'Average' values.	
    # This option allows you to override the metric type. 
    #
    # Allowed statTypes are: ave, max, min, sum, samplecount
    #
    # Note: Irrespective of the metric type, value will still be reported as
    # Observed value to the Controller
   includeMetrics:
     - name: "ProvisionedReadCapacityUnits"
       alias: "Provisioned Read Capacity Units"
       statType: "sum"
       aggregationType: "AVERAGE"
       timeRollUpType: "AVERAGE"
       clusterRollUpType: "INDIVIDUAL"
       delta: false
       multiplier: 1
     - name: "ConsumedReadCapacityUnits"
       alias: "Consumed Read Capacity Units"
       statType: "ave"
       aggregationType: "AVERAGE"
       timeRollUpType: "AVERAGE"
       clusterRollUpType: "INDIVIDUAL"
       delta: false
       multiplier: 1

   metricsTimeRange:
     startTimeInMinsBeforeNow: 5
     endTimeInMinsBeforeNow: 0

   # Rate limit ( per second ) for GetMetricStatistics, default value is 400. https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html
   getMetricStatisticsRateLimit: 400

    # 
    # The max number of retry attempts for failed retryable requests 
    # (ex: 5xx error responses from a service) or throttling errors
    #
   maxErrorRetrySize: 0

concurrencyConfig:
  noOfAccountThreads: 3
  noOfRegionThreadsPerAccount: 3
  noOfMetricThreadsPerRegion: 3
  #Thread timeout in seconds
  threadTimeOut: 30


#Allowed values are Basic and Detailed. Refer https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-cloudwatch-new.html for more information
# Basic will fire CloudWatch API calls every 5 minutes
# Detailed will fire CloudWatch API calls every 1 minutes
cloudWatchMonitoring: "Basic"

regionEndPoints:
  us-east-1 : monitoring.us-east-1.amazonaws.com
  us-east-2 : monitoring.us-east-2.amazonaws.com
  us-west-1 : monitoring.us-west-1.amazonaws.com
  us-west-2 : monitoring.us-west-2.amazonaws.com
  ap-northeast-1 : monitoring.ap-northeast-1.amazonaws.com
  ap-northeast-2: monitoring.ap-northeast-2.amazonaws.com
  ap-northeast-3 : monitoring.ap-northeast-3.amazonaws.com
  ap-south-1 : monitoring.ap-south-1.amazonaws.com
  ap-southeast-1 : monitoring.ap-southeast-1.amazonaws.com
  ap-southeast-2 : monitoring.ap-southeast-2.amazonaws.com
  ca-central-1 : monitoring.ca-central-1.amazonaws.com
  cn-north-1 : monitoring.cn-north-1.amazonaws.com.cn
  cn-northwest-1 : monitoring.cn-northwest-1.amazonaws.com.cn
  eu-central-1 : monitoring.eu-central-1.amazonaws.com
  eu-west-1 : monitoring.eu-west-1.amazonaws.com
  eu-west-2 : monitoring.eu-west-2.amazonaws.com
  eu-west-3 : monitoring.eu-west-3.amazonaws.com
  sa-east-1 : monitoring.sa-east-1.amazonaws.com
  us-gov-west-1 : monitoring.us-gov-west-1.amazonaws.com